name: flutter_axelor_sdk
description: Powerful, helpfull, extensible and highly customizable API's that wrap http client to make communication easier with Axelor server with boilerplate code free.
version: 0.0.1
repository: https://github.com/Abdktefane/flutter-axelor-sdk
issue_tracker: https://github.com/Abdktefane/flutter-axelor-sdk/issues
homepage: https://github.com/Abdktefane/flutter-axelor-sdk
documentation: https://github.com/Abdktefane/flutter-axelor-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Data
  equatable: ^2.0.3
  dio: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter:
